In [4]:
import pandas as pd
from IPython.display import display

In [2]:
df = pd.read_csv('../data/dados_covid.csv')

In [3]:
df.head()

,city,city_ibge_code,date,epidemiological_week,estimated_population_2019,is_last,is_repeated,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,new_confirmed,new_deaths,order_for_place,place_type,state
0,Abaíra,2900108.0,2020-07-13,29,8739.0,True,False,5,57.21478,2020-07-13,0.0000,0,0,0,92,city,BA
1,Abaré,2900207.0,2020-07-13,29,20086.0,True,False,5,24.89296,2020-07-13,0.0000,0,0,0,60,city,BA
2,Acajutiba,2900306.0,2020-07-13,29,15159.0,True,False,41,270.46639,2020-07-13,0.0488,2,0,0,83,city,BA
3,Adustina,2900355.0,2020-07-13,29,17040.0,True,False,47,275.82160,2020-07-13,0.0213,1,3,0,101,city,BA
4,Água Fria,2900405.0,2020-07-13,29,16970.0,True,False,39,229.81732,2020-07-13,0.0256,1,2,0,84,city,BA

In [5]:
cols = [
    'epidemiological_week', 'estimated_population_2019',
    'is_repeated', 'order_for_place', 'state'
]
temp = df.drop(cols, axis=1).copy()
display(temp[(temp['city'] == 'Candiba') & (temp['is_last'] == True)])

# Drop Importados cases
# temp = temp[temp['city'] != 'Importados/Indefinidos']
temp = temp.drop(temp[temp['city'] == 'Importados/Indefinidos'].index)
display(temp[temp['city'] == 'Candiba'].head())

,city,city_ibge_code,date,is_last,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,new_confirmed,new_deaths,place_type
76,Candiba,2906600.0,2020-07-13,True,15,104.75592,2020-07-13,0.0,0,0,0,city

,city,city_ibge_code,date,is_last,last_available_confirmed,last_available_confirmed_per_100k_inhabitants,last_available_date,last_available_death_rate,last_available_deaths,new_confirmed,new_deaths,place_type
76,Candiba,2906600.0,2020-07-13,True,15,104.75592,2020-07-13,0.0,0,0,0,city
486,Candiba,2906600.0,2020-07-12,False,15,104.75592,2020-07-12,0.0,0,0,0,city
896,Candiba,2906600.0,2020-07-11,False,15,104.75592,2020-07-11,0.0,0,1,0,city
1305,Candiba,2906600.0,2020-07-10,False,14,97.77219,2020-07-10,0.0,0,1,0,city
1714,Candiba,2906600.0,2020-07-09,False,13,90.78846,2020-07-09,0.0,0,0,0,city